version: "3.9"

services:
  boston-api:
    build: .
    container_name: boston-housing-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
